// Automatically generated by make_root_pointers.py.

const char *readline_hist[(8)];
mp_obj_list_t mp_sys_argv_obj;
mp_obj_t bluetooth;
mp_obj_t dupterm_objs[(1)];
mp_obj_t machine_pin_irq_handler[(40)];
mp_obj_t native_code_pointers;
mp_obj_t sys_mutable[MP_SYS_MUTABLE_NUM];
mp_sched_item_t sched_queue[(8)];
struct _esp_espnow_obj_t *espnow_singleton;
struct _machine_i2s_obj_t *machine_i2s_obj[I2S_NUM_AUTO];
struct _machine_timer_obj_t *machine_timer_obj_head;
struct _mp_bluetooth_nimble_root_pointers_t *bluetooth_nimble_root_pointers;
struct _mp_vfs_mount_t *vfs_cur;
struct _mp_vfs_mount_t *vfs_mount_table;
